---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Contribua com conteúdo
    url: "/index.html"
  - title: Estilo para documentos NetApp
    url: "/style.html"
  - title: Referência AsciiDoc
    url: "/asciidoc_syntax.html"
  - title: Política sobre conteúdo gerado por IA
    url: "/ai-policy.html"
  - title: Avisos legais
    url: "/legal-notices.html"
